# Project information
site_name: html
site_url: https://html.wiki.wanwusangzhi.top/
site_author: wanwusangzhi
site_description: html学习笔记
site_dir: site
# Repository
repo_name: pymanim/htmlwiki
repo_url: https://github.com/pymanim/htmlwiki
edit_uri: tree/main/docs
#version: 1.0.0

# Copyright
copyright: Copyright &copy; 2024 wanwusangzhi<br>my website is at <a href="http://www.wanwusangzhi.top">web</a>

# Configuration
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.indexes
    - navigation.expand
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: 深色模式
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: 浅色模式
  font:
    text: Noto Sans SC
    code: Fira Code
  favicon: /favicon.jpg
  logo: /icon.svg
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: fontawesome/regular/pen-to-square
# Plugins
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      auto_caption: false
      caption_position: bottom

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - 简介: index.md
  - 序:
    - 0.0 &nbsp; 概述: 0pre/index.md
    - 0.1 &nbsp; 如何呈现: 0pre/how.md
  - html简介:
    - 1.1 &nbsp; html概述: 1intro/index.md
    - 1.1 &nbsp; 简介: 1intro/introduction.md

#- 第 1 章 &nbsp; 初识算法:
    # [icon: material/calculator-variant-outline]
#    - chapter_introduction/index.md
#    - 1.1 &nbsp; 算法无处不在: chapter_introduction/algorithms_are_everywhere.md
#    - 1.2 &nbsp; 算法是什么: chapter_introduction/what_is_dsa.md
#    - 1.3 &nbsp; 小结: chapter_introduction/summary.md